---
templateDir: .openapi-generator/templates
additionalProperties:
  packageName: raiffeisenbank_client
  projectName: raiffeisenbank_client
  apiPackage: RaiffeisenBank
  UserId: VitexSoftware
  RepoId: php-vitexsoftware-raiffeisenbank
  infoEmail: info@vitexsoftware.cz
files:
  AUTHORS.md: {}
  composer.json: {}
