---
templateDir: .openapi-generator/templates
additionalProperties:
  packageName: Raiffeisenbank Premium API client library
  apiPackage: PremiumAPI
  UserId: VitexSoftware
  RepoId: php-vitexsoftware-rbczpremiumapi
  infoEmail: info@vitexsoftware.cz
  allowUnicodeIdentifiers: true
  artifactVersion: 0.1.0
  invokerPackage: VitexSoftware\Raiffeisenbank
  modelPackage: Model
  variableNamingConvention: camelCase
files:
  AUTHORS.md: {}
  composer.json: {}
  ApiClient.php: 
      folder: lib
  bootstrap.php:
      folder: test

